name = "OpenAIGym"
uuid = "41d6fcb8-dd24-11e8-2536-c3dc023218b5"
authors = ["Tom Breloff <tom@breloff.com>", "Joel Mason <jobba1@hotmail.com>", "Iblis Lin <iblis@hs.ntnu.edu.tw>"]
version = "0.1.0"

[deps]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Reinforce = "0376cc21-f8a9-5fcf-8891-fde1415a4fd3"

[compat]
Reinforce = "~0.2"
julia = "â‰¥0.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
